// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/cordova-ionic/cordova-ionic.d.ts
// Type definitions for Ionic Cordova plugins
// Project: https://github.com/driftyco
// Definitions by: Hendrik Maus <https://github.com/hendrikmaus>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


interface CordovaPlugins {
  Keyboard:Ionic.Keyboard;
}